version: 2

jobs:
  build:
    environment:
      GITHUB_ORG: https://github.com/angular-schule
      GITHUB_NAME: The Buildbot
      GITHUB_EMAIL: buildbot@angular2buch.de
      NAME: angular-cli-ghpages

    docker:
      - image: circleci/node:14-browsers

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "src/package.json" }}
      - run: cd src && npm i --silent
      - save_cache:
          key: dependency-cache-{{ checksum "src/package.json" }}
          paths:
            - src/node_modules
      - run: cd src && npm run build
      - run: cd src && npm run test
      - run: cd src/dist && sudo npm link

      - run: sudo -E npm install -g @angular/cli@next
      - run: sudo -E ng new your-angular-project --defaults
      - run: cd your-angular-project && sudo -E npm link angular-cli-ghpages
      - run: cd your-angular-project && sudo -E ng add angular-cli-ghpages
      - run: cd your-angular-project && sudo -E ng deploy --repo="$GITHUB_ORG/$NAME.git" --name="$GITHUB_NAME" --email="$GITHUB_EMAIL" --cname=angular-cli-ghpages.angular.schule


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
